# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

version: 1

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.builddate={{ .Date }} -X main.gitref={{ .Version }}
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: 386

    main: ./cmd/we

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: ionrock
    name: we

  prerelease: auto

brews:
  - name: we
    homepage: https://github.com/ionrock/we
    description: Apply YAML/JSON env files before running commands
    repository:
      owner: ionrock
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    install: |
      bin.install "we"
    test: |
      system "#{bin}/we", "--version"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
