name: Release Binaries

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  releases-matrix:
    name: release binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, win]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.40
        with:
          github_token: ${{ secrets.pat }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./cmd/we"
          binary_name: "we"
